require_relative "swm/version"
require_relative "swm/window"
require_relative "swm/screen"
require_relative "swm/command_runner"
require_relative "swm/commands/command"
require_relative "swm/commands/resize_command"
require_relative "swm/commands/move_command"
